[package]
name = "minety"
version = "0.1.0"
authors = ["Jota Lanusse <jotalanusse@gmail.com>", "Iñaki Arango <arangoinaki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
